# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.models.list_company_users200_response_inner import ListCompanyUsers200ResponseInner

class TestListCompanyUsers200ResponseInner(unittest.TestCase):
    """ListCompanyUsers200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCompanyUsers200ResponseInner:
        """Test ListCompanyUsers200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCompanyUsers200ResponseInner`
        """
        model = ListCompanyUsers200ResponseInner()
        if include_optional:
            return ListCompanyUsers200ResponseInner(
                company_id = 1,
                user_id = 10,
                role = 'viewer',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user = multiflexi_client.models.user.User(
                    id = 10, 
                    enabled = True, 
                    settings = '', 
                    email = '', 
                    firstname = '', 
                    lastname = '', 
                    password = '', 
                    login = '', 
                    dat_create = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dat_save = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_modifier_id = 10, )
            )
        else:
            return ListCompanyUsers200ResponseInner(
        )
        """

    def testListCompanyUsers200ResponseInner(self):
        """Test ListCompanyUsers200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
