# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.models.unassign_user_from_company200_response import UnassignUserFromCompany200Response

class TestUnassignUserFromCompany200Response(unittest.TestCase):
    """UnassignUserFromCompany200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnassignUserFromCompany200Response:
        """Test UnassignUserFromCompany200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnassignUserFromCompany200Response`
        """
        model = UnassignUserFromCompany200Response()
        if include_optional:
            return UnassignUserFromCompany200Response(
                company_id = 56,
                user_id = 56,
                deleted = 56
            )
        else:
            return UnassignUserFromCompany200Response(
        )
        """

    def testUnassignUserFromCompany200Response(self):
        """Test UnassignUserFromCompany200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
