# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.models.set_user_roles200_response import SetUserRoles200Response

class TestSetUserRoles200Response(unittest.TestCase):
    """SetUserRoles200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetUserRoles200Response:
        """Test SetUserRoles200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetUserRoles200Response`
        """
        model = SetUserRoles200Response()
        if include_optional:
            return SetUserRoles200Response(
                user_id = 56,
                replace = True,
                roles = [
                    ''
                    ],
                role_details = [
                    multiflexi_client.models.rbac_role.RbacRole(
                        id = 1, 
                        name = 'admin', 
                        display_name = 'Administrator', 
                        is_active = True, 
                        assigned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return SetUserRoles200Response(
        )
        """

    def testSetUserRoles200Response(self):
        """Test SetUserRoles200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
