# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.models.test_event_source_connection200_response import TestEventSourceConnection200Response

class TestTestEventSourceConnection200Response(unittest.TestCase):
    """TestEventSourceConnection200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestEventSourceConnection200Response:
        """Test TestEventSourceConnection200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestEventSourceConnection200Response`
        """
        model = TestEventSourceConnection200Response()
        if include_optional:
            return TestEventSourceConnection200Response(
                reachable = True,
                message = ''
            )
        else:
            return TestEventSourceConnection200Response(
        )
        """

    def testTestEventSourceConnection200Response(self):
        """Test TestEventSourceConnection200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
