# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.models.assign_user_to_company_request import AssignUserToCompanyRequest

class TestAssignUserToCompanyRequest(unittest.TestCase):
    """AssignUserToCompanyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssignUserToCompanyRequest:
        """Test AssignUserToCompanyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssignUserToCompanyRequest`
        """
        model = AssignUserToCompanyRequest()
        if include_optional:
            return AssignUserToCompanyRequest(
                user_id = 10,
                role = 'viewer'
            )
        else:
            return AssignUserToCompanyRequest(
                user_id = 10,
        )
        """

    def testAssignUserToCompanyRequest(self):
        """Test AssignUserToCompanyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
