# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.api.eventrule_api import EventruleApi


class TestEventruleApi(unittest.TestCase):
    """EventruleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventruleApi()

    def tearDown(self) -> None:
        pass

    def test_delete_event_rule_by_id(self) -> None:
        """Test case for delete_event_rule_by_id

        Delete EventRule by ID
        """
        pass

    def test_get_event_rule_by_id(self) -> None:
        """Test case for get_event_rule_by_id

        Get EventRule by ID
        """
        pass

    def test_list_event_rules(self) -> None:
        """Test case for list_event_rules

        Show All EventRules
        """
        pass

    def test_set_event_rule_by_id(self) -> None:
        """Test case for set_event_rule_by_id

        Create or Update EventRule
        """
        pass


if __name__ == '__main__':
    unittest.main()
