# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.api.credential_api import CredentialApi


class TestCredentialApi(unittest.TestCase):
    """CredentialApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CredentialApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_user_credentials(self) -> None:
        """Test case for get_all_user_credentials

        Get All User Credentials
        """
        pass

    def test_get_credential(self) -> None:
        """Test case for get_credential

        Get User Credentials
        """
        pass

    def test_update_credentials(self) -> None:
        """Test case for update_credentials

        Update Credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
