# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.api.user_company_api import UserCompanyApi


class TestUserCompanyApi(unittest.TestCase):
    """UserCompanyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserCompanyApi()

    def tearDown(self) -> None:
        pass

    def test_assign_user_to_company(self) -> None:
        """Test case for assign_user_to_company

        Assign a user to a company
        """
        pass

    def test_list_company_users(self) -> None:
        """Test case for list_company_users

        List users assigned to a company
        """
        pass

    def test_unassign_user_from_company(self) -> None:
        """Test case for unassign_user_from_company

        Remove a user from a company
        """
        pass


if __name__ == '__main__':
    unittest.main()
