# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from multiflexi_client.api.eventsource_api import EventsourceApi


class TestEventsourceApi(unittest.TestCase):
    """EventsourceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsourceApi()

    def tearDown(self) -> None:
        pass

    def test_delete_event_source_by_id(self) -> None:
        """Test case for delete_event_source_by_id

        Delete EventSource by ID
        """
        pass

    def test_get_event_source_by_id(self) -> None:
        """Test case for get_event_source_by_id

        Get EventSource by ID
        """
        pass

    def test_list_event_sources(self) -> None:
        """Test case for list_event_sources

        Show All EventSources
        """
        pass

    def test_set_event_source_by_id(self) -> None:
        """Test case for set_event_source_by_id

        Create or Update EventSource
        """
        pass

    def test_test_event_source_connection(self) -> None:
        """Test case for test_event_source_connection

        Test EventSource connection
        """
        pass


if __name__ == '__main__':
    unittest.main()
