# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class EventRule(BaseModel):
    """
    EventRule
    """ # noqa: E501
    id: Optional[StrictInt] = None
    event_source_id: Optional[StrictInt] = Field(default=None, description="References EventSource")
    evidence: Optional[Annotated[str, Field(strict=True, max_length=60)]] = Field(default=None, description="Evidence type pattern to match (null = any)")
    operation: Optional[StrictStr] = Field(default='any', description="Operation to match")
    runtemplate_id: Optional[StrictInt] = Field(default=None, description="RunTemplate ID to trigger when rule matches")
    priority: Optional[StrictInt] = Field(default=0, description="Higher priority rules are evaluated first")
    enabled: Optional[StrictBool] = Field(default=True, description="Whether this rule is active")
    env_mapping: Optional[StrictStr] = Field(default=None, description="JSON mapping of change fields to environment variables")
    created: Optional[datetime] = None
    modified: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "event_source_id", "evidence", "operation", "runtemplate_id", "priority", "enabled", "env_mapping", "created", "modified"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'create', 'update', 'delete']):
            raise ValueError("must be one of enum values ('any', 'create', 'update', 'delete')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if evidence (nullable) is None
        # and model_fields_set contains the field
        if self.evidence is None and "evidence" in self.model_fields_set:
            _dict['evidence'] = None

        # set to None if env_mapping (nullable) is None
        # and model_fields_set contains the field
        if self.env_mapping is None and "env_mapping" in self.model_fields_set:
            _dict['env_mapping'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "event_source_id": obj.get("event_source_id"),
            "evidence": obj.get("evidence"),
            "operation": obj.get("operation") if obj.get("operation") is not None else 'any',
            "runtemplate_id": obj.get("runtemplate_id"),
            "priority": obj.get("priority") if obj.get("priority") is not None else 0,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "env_mapping": obj.get("env_mapping"),
            "created": obj.get("created"),
            "modified": obj.get("modified")
        })
        return _obj


