# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class EventSource(BaseModel):
    """
    EventSource
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Human-readable name for this event source")
    adapter_type: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Type of webhook adapter")
    db_connection: Optional[Annotated[str, Field(strict=True, max_length=16)]] = Field(default='mysql', description="Database driver")
    db_host: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default='localhost', description="Database host")
    db_port: Optional[Annotated[str, Field(strict=True, max_length=8)]] = Field(default='3306', description="Database port")
    db_database: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Database name")
    db_username: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Database username")
    db_password: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Database password")
    poll_interval: Optional[StrictInt] = Field(default=60, description="How often to poll for new changes (seconds)")
    enabled: Optional[StrictBool] = Field(default=True, description="Whether this source is active")
    last_processed_id: Optional[StrictInt] = Field(default=0, description="Last processed change inversion ID")
    created: Optional[datetime] = None
    modified: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "adapter_type", "db_connection", "db_host", "db_port", "db_database", "db_username", "db_password", "poll_interval", "enabled", "last_processed_id", "created", "modified"]

    @field_validator('db_connection')
    def db_connection_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['mysql', 'pgsql', 'sqlite']):
            raise ValueError("must be one of enum values ('mysql', 'pgsql', 'sqlite')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "adapter_type": obj.get("adapter_type"),
            "db_connection": obj.get("db_connection") if obj.get("db_connection") is not None else 'mysql',
            "db_host": obj.get("db_host") if obj.get("db_host") is not None else 'localhost',
            "db_port": obj.get("db_port") if obj.get("db_port") is not None else '3306',
            "db_database": obj.get("db_database"),
            "db_username": obj.get("db_username"),
            "db_password": obj.get("db_password"),
            "poll_interval": obj.get("poll_interval") if obj.get("poll_interval") is not None else 60,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "last_processed_id": obj.get("last_processed_id") if obj.get("last_processed_id") is not None else 0,
            "created": obj.get("created"),
            "modified": obj.get("modified")
        })
        return _obj


