# coding: utf-8

"""
    MultiFlexi API

    MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from multiflexi_client.models.job import Job
from typing import Optional, Set
from typing_extensions import Self

class Task(BaseModel):
    """
    Task
    """ # noqa: E501
    id: Optional[StrictInt] = None
    runtemplate_id: Optional[StrictInt] = Field(default=None, description="FK to the RunTemplate that spawned this task")
    window_start: Optional[datetime] = Field(default=None, description="Start of the scheduling window")
    window_end: Optional[datetime] = Field(default=None, description="End of the scheduling window")
    deadline: Optional[datetime] = Field(default=None, description="Deadline by which the result must be ready")
    state: Optional[StrictStr] = Field(default=None, description="Current task state")
    fulfilled_by_job_id: Optional[StrictInt] = Field(default=None, description="ID of the job that fulfilled this task")
    fulfilled_at: Optional[datetime] = Field(default=None, description="When the task was fulfilled")
    attempts: Optional[StrictInt] = Field(default=None, description="Number of job attempts made")
    created_at: Optional[datetime] = None
    jobs: Optional[List[Job]] = Field(default=None, description="Job attempt history (only present in single-task responses)")
    __properties: ClassVar[List[str]] = ["id", "runtemplate_id", "window_start", "window_end", "deadline", "state", "fulfilled_by_job_id", "fulfilled_at", "attempts", "created_at", "jobs"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['open', 'running', 'fulfilled', 'fulfilled_late', 'failed', 'missed']):
            raise ValueError("must be one of enum values ('open', 'running', 'fulfilled', 'fulfilled_late', 'failed', 'missed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Task from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in jobs (list)
        _items = []
        if self.jobs:
            for _item_jobs in self.jobs:
                if _item_jobs:
                    _items.append(_item_jobs.to_dict())
            _dict['jobs'] = _items
        # set to None if fulfilled_by_job_id (nullable) is None
        # and model_fields_set contains the field
        if self.fulfilled_by_job_id is None and "fulfilled_by_job_id" in self.model_fields_set:
            _dict['fulfilled_by_job_id'] = None

        # set to None if fulfilled_at (nullable) is None
        # and model_fields_set contains the field
        if self.fulfilled_at is None and "fulfilled_at" in self.model_fields_set:
            _dict['fulfilled_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Task from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "runtemplate_id": obj.get("runtemplate_id"),
            "window_start": obj.get("window_start"),
            "window_end": obj.get("window_end"),
            "deadline": obj.get("deadline"),
            "state": obj.get("state"),
            "fulfilled_by_job_id": obj.get("fulfilled_by_job_id"),
            "fulfilled_at": obj.get("fulfilled_at"),
            "attempts": obj.get("attempts"),
            "created_at": obj.get("created_at"),
            "jobs": [Job.from_dict(_item) for _item in obj["jobs"]] if obj.get("jobs") is not None else None
        })
        return _obj


